spring:
  application:
    name: hav.imobiliaria
  datasource:
      urL: jdbc:mysql://localhost:3306/db_hav?createDatabaseIfNotExist=true
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
server:
  port: 8082
aws:
  access-key: AKIA2AUOPIM3J2WOGT5N
  secret-key: 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
  region: us-east-1
  bucket-name: hav-bucket-c