spring:
  application:
    name: hav.imobiliaria
  datasource:
    url: jdbc:h2:file:C:/Users/carlos_kviatkowsky/db_hav;AUTO_SERVER=TRUE  # URL do banco de dados H2 em memória
    driverClassName: org.h2.Driver  # Driver do H2
    username: sa  # Usuário padrão do H2
    password: password  # Sen'ha padrão do H2
  h2:
    console:
      enabled: true  # Habilita o console do H2
      path: /h2-console  # Caminho para acessar o console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # Dialeto do Hibernate para H2
    hibernate:
      ddl-auto: update
    h2:
      console:
        enabled: true
        path: /h2-console
server:
  port: 8081