spring:
   application:
      name: hav.imobiliaria
   datasource:
      urL: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/db_hav_dev?createDatabaseIfNotExist=true}
      username: ${DATASOURCE_USERNAME:root}
      password: ${DATASOURCE_PASSWORD:}
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
   mail:
      host: smtp.gmail.com
      port: 587
      username: hav.imobiliaria@gmail.com
      password: ${EMAIL_APP_PASSWORD}
      protocol: smtp
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      check-template-location: true
      cache: false
   servlet:
      multipart:
         max-request-size: 20MB
         max-file-size: 20MB
server:
   port: 8082
aws:
   access-key: ${S3_ACCESS_KEY}
   secret-key: ${S3_SECRET_KEY}
   region: ${S3_REGION}
   bucket-name: ${S3_BUCKET_NAME}
api:
  security :
    token:
      secret: ${TOKEN_PASSWORD}
springdoc:
   swagger-ui:
      path: /swagger-ui.html


#Producao
---

spring:
  config:
    activate:
       on-profile: production
  jpa:
     show-sql: false


# Homologacao

---


spring:
   config:
      activate:
         on-profile: homologacao
   jpa:
      show-sql: false
   datasource:
      url: jdbc:mysql://localhost:3306/db_hav_homolog



