spring:
  application:
    name: hav.imobiliaria
  datasource:
    urL: jdbc:mysql://localhost:3306/db_hav?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
server:
  port: 8081
aws:
  access-key: a
  secret-key: a
  region: us-east-1
  bucket-name: hav-bucket-c